export const runtime='edge';
import { NextRequest } from 'next/server';
const DEFAULT_DOH='cloudflare-dns.com';
const dohHost=(process.env.DOH||DEFAULT_DOH).replace(/^https?:\/\//,'').split('/')[0];
function cors(h=new Headers()){h.set('access-control-allow-origin','*');h.set('access-control-allow-methods','GET, POST, OPTIONS');h.set('access-control-allow-headers','*');return h;}
async function fetchText(u,i){const r=await fetch(u,i);const t=await r.text();return {ok:r.ok,status:r.status,statusText:r.statusText,text:t,headers:r.headers};}
async function queryUpstreamSmart(dohBase,name,type){const u=new URL(dohBase);const host=u.hostname.toLowerCase();const tryGoogle=async()=>{const g=new URL(dohBase);g.pathname='/resolve';g.searchParams.set('name',name);g.searchParams.set('type',type);return fetchText(g.toString(),{headers:{'accept':'application/dns-json','user-agent':'HongShi-DoH/edge'}})};const tryCf=async()=>{const c=new URL(dohBase);c.pathname='/dns-query';c.searchParams.set('name',name);c.searchParams.set('type',type);c.searchParams.set('ct','application/dns-json');return fetchText(c.toString(),{headers:{'accept':'application/dns-json','user-agent':'HongShi-DoH/edge'}})};const pri=host.includes('dns.google')?await tryGoogle():await tryCf();if(pri.ok)return pri;const fb=host.includes('dns.google')?await tryCf():await tryGoogle();return fb.ok?fb:pri;}
export async function GET(req){
  const url=new URL(req.url); const path=url.pathname;
  if(path==='/'){return new Response('<!doctype html><meta charset="utf-8"><title>HongShi-DoH</title><p>主页可用。前往 <a href="/ui/">UI</a></p>',{headers:{'content-type':'text/html; charset=utf-8'}})}
  if(path==='/meta'){const dohPath=process.env.DOH_PATH||process.env.HSD_PATH||process.env.TOKEN||'dns-query';const dnsQueryEnabled=dohPath==='dns-query';return new Response(JSON.stringify({dohPath,dnsQueryEnabled},null,2),{headers:cors(new Headers({'content-type':'application/json'}))})}
  if(path==='/ip'){const ip=req.headers.get('x-real-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'0.0.0.0';const base={ip,country_code:req.headers.get('x-vercel-ip-country')||undefined,province_code:req.headers.get('x-vercel-ip-country-region')||undefined,city:req.headers.get('x-vercel-ip-city')||undefined,latitude:req.headers.get('x-vercel-ip-latitude')||undefined,longitude:req.headers.get('x-vercel-ip-longitude')||undefined,timezone:req.headers.get('x-vercel-ip-timezone')||undefined,isp:undefined,asn:undefined,source:{platform:'vercel',enriched:false,provider:null}};return new Response(JSON.stringify(base,null,2),{headers:cors(new Headers({'content-type':'application/json'}))})}
  if(path==='/host'){const hostname=process.env.HOSTNAME||undefined;const region=process.env.VERCEL_REGION||undefined;const vercelUrl=process.env.VERCEL_URL||undefined;return new Response(JSON.stringify({platform:'vercel',hostname,region,url:vercelUrl},null,2),{headers:{'content-type':'application/json','access-control-allow-origin':'*'}})}
  if(path==='/resolve'){const name=url.searchParams.get('name');const type=url.searchParams.get('type')||'A';const doh=url.searchParams.get('doh')||'';if(!name)return new Response(JSON.stringify({error:'name required'}),{status:400,headers:{'content-type':'application/json'}});const origin=`${url.protocol}//${url.host}`;if(!doh||doh.startsWith(origin)){const baseHost=(process.env.DOH||DEFAULT_DOH).replace(/^https?:\/\//,'').split('/')[0];const mk=(t)=>{const base=new URL(`https://${baseHost}`);const isGoogle=base.hostname.includes('dns.google');if(isGoogle)base.pathname='/resolve';else{base.pathname='/dns-query';base.searchParams.set('ct','application/dns-json');}base.searchParams.set('name',name);base.searchParams.set('type',t);return base.toString();};const [a4,a6,ns]=await Promise.all([fetchText(mk('A')),fetchText(mk('AAAA')),fetchText(mk('NS'))]);const parse=(x)=>{try{return JSON.parse(x.text)}catch{return {raw:x.text}}};if(!a4.ok&&!a6.ok&&!ns.ok)return new Response(JSON.stringify({error:'all upstream failed',a4,a6,ns}),{status:502,headers:cors(new Headers({'content-type':'application/json'}))});const j4=a4.ok?parse(a4):{};const j6=a6.ok?parse(a6):{};const js=ns.ok?parse(ns):{};const nsRecords=[];(js.Answer||[]).forEach(r=>{if(r.type===2)nsRecords.push(r)});(js.Authority||[]).forEach(r=>{if(r.type===2||r.type===6)nsRecords.push(r)});const merged={Status:j4.Status||j6.Status||js.Status||0,Question:[].concat(j4.Question||[],j6.Question||[],js.Question||[]),Answer:[].concat(j4.Answer||[],j6.Answer||[],nsRecords)};return new Response(JSON.stringify(merged,null,2),{headers:cors(new Headers({'content-type':'application/json','cache-control':'no-store'}))})}const out=await queryUpstreamSmart(doh,name,type);if(!out.ok)return new Response(JSON.stringify({error:'upstream error',status:out.status,statusText:out.statusText,body:out.text.slice(0,400)}),{status:502,headers:cors(new Headers({'content-type':'application/json'}))});return new Response(out.text,{headers:cors(new Headers({'content-type':'application/json','cache-control':'no-store'}))})}
  if(path==='/ui') return new Response('',{status:302,headers:{Location:'/ui/'}});
  return new Response('Not Found',{status:404,headers:cors()});
}
export async function POST(){return new Response('Not Found',{status:404,headers:cors()});}
export async function OPTIONS(){return new Response(null,{status:204,headers:cors()});}